namespace PlxParser
{
    partial class MainForm
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
                components.Dispose();
            base.Dispose(disposing);
        }
        private void InitializeComponent()
        {
            this.tabControl = new System.Windows.Forms.TabControl();
            this.tabImport = new System.Windows.Forms.TabPage();
            this.tabPlans = new System.Windows.Forms.TabPage();
            this.tabWorkload = new System.Windows.Forms.TabPage();
            this.tabSettings = new System.Windows.Forms.TabPage();
            this.btnSelectFile = new System.Windows.Forms.Button();
            this.txtFilePath = new System.Windows.Forms.TextBox();
            this.btnImport = new System.Windows.Forms.Button();
            this.txtLog = new System.Windows.Forms.RichTextBox();
            this.lblFilePath = new System.Windows.Forms.Label();
            this.lblDescription = new System.Windows.Forms.Label();
            this.txtDescription = new System.Windows.Forms.TextBox();
            this.dgvPlans = new System.Windows.Forms.DataGridView();
            this.btnDeletePlan = new System.Windows.Forms.Button();
            this.btnRefreshPlans = new System.Windows.Forms.Button();
            this.lblSpeciality = new System.Windows.Forms.Label();
            this.cmbSpeciality = new System.Windows.Forms.ComboBox();
            this.clbSpecialities = new System.Windows.Forms.CheckedListBox();
            this.lblSelectPlans = new System.Windows.Forms.Label();
            this.lblGroup = new System.Windows.Forms.Label();
            this.cmbGroup = new System.Windows.Forms.ComboBox();
            this.lblYear = new System.Windows.Forms.Label();
            this.numYear = new System.Windows.Forms.NumericUpDown();
            this.lblMode = new System.Windows.Forms.Label();
            this.cmbMode = new System.Windows.Forms.ComboBox();
            this.lblCourse = new System.Windows.Forms.Label();
            this.cmbCourse = new System.Windows.Forms.ComboBox();
            this.btnCalculate = new System.Windows.Forms.Button();
            this.tabResults = new System.Windows.Forms.TabControl();
            this.tabDisciplines = new System.Windows.Forms.TabPage();
            this.tabDepartments = new System.Windows.Forms.TabPage();
            this.dgvResults = new System.Windows.Forms.DataGridView();
            this.dgvDepartments = new System.Windows.Forms.DataGridView();
            this.lblSp = new System.Windows.Forms.Label();
            this.lblSpValue = new System.Windows.Forms.Label();
            this.grpFormula = new System.Windows.Forms.GroupBox();
            this.lblSpecSettings = new System.Windows.Forms.Label();
            this.cmbSpecSettings = new System.Windows.Forms.ComboBox();
            this.lblYearSettings = new System.Windows.Forms.Label();
            this.numYearSettings = new System.Windows.Forms.NumericUpDown();
            this.lblStudentsPerRate = new System.Windows.Forms.Label();
            this.numStudentsPerRate = new System.Windows.Forms.NumericUpDown();
            this.lblHoursCW = new System.Windows.Forms.Label();
            this.numHoursCW = new System.Windows.Forms.NumericUpDown();
            this.lblHoursCP = new System.Windows.Forms.Label();
            this.numHoursCP = new System.Windows.Forms.NumericUpDown();
            this.lblHoursGW = new System.Windows.Forms.Label();
            this.numHoursGW = new System.Windows.Forms.NumericUpDown();
            this.btnSaveFormula = new System.Windows.Forms.Button();
            this.grpGroups = new System.Windows.Forms.GroupBox();
            this.lblGroupName = new System.Windows.Forms.Label();
            this.txtGroupName = new System.Windows.Forms.TextBox();
            this.lblGroupProfile = new System.Windows.Forms.Label();
            this.cmbGroupProfile = new System.Windows.Forms.ComboBox();
            this.btnAddGroup = new System.Windows.Forms.Button();
            this.btnDeleteGroup = new System.Windows.Forms.Button();
            this.grpStudents = new System.Windows.Forms.GroupBox();
            this.lblStudentGroup = new System.Windows.Forms.Label();
            this.cmbStudentGroup = new System.Windows.Forms.ComboBox();
            this.lblStudentYear = new System.Windows.Forms.Label();
            this.numStudentYear = new System.Windows.Forms.NumericUpDown();
            this.lblStudentCount = new System.Windows.Forms.Label();
            this.numStudentCount = new System.Windows.Forms.NumericUpDown();
            this.btnSaveStudents = new System.Windows.Forms.Button();
            this.tabControl.SuspendLayout();
            this.tabImport.SuspendLayout();
            this.tabPlans.SuspendLayout();
            this.tabWorkload.SuspendLayout();
            this.tabSettings.SuspendLayout();
            this.tabResults.SuspendLayout();
            this.tabDisciplines.SuspendLayout();
            this.tabDepartments.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)this.numYear).BeginInit();
            ((System.ComponentModel.ISupportInitialize)this.dgvResults).BeginInit();
            ((System.ComponentModel.ISupportInitialize)this.dgvDepartments).BeginInit();
            ((System.ComponentModel.ISupportInitialize)this.dgvPlans).BeginInit();
            ((System.ComponentModel.ISupportInitialize)this.numYearSettings).BeginInit();
            ((System.ComponentModel.ISupportInitialize)this.numStudentsPerRate).BeginInit();
            ((System.ComponentModel.ISupportInitialize)this.numHoursCW).BeginInit();
            ((System.ComponentModel.ISupportInitialize)this.numHoursCP).BeginInit();
            ((System.ComponentModel.ISupportInitialize)this.numHoursGW).BeginInit();
            ((System.ComponentModel.ISupportInitialize)this.numStudentYear).BeginInit();
            ((System.ComponentModel.ISupportInitialize)this.numStudentCount).BeginInit();
            this.grpFormula.SuspendLayout();
            this.grpGroups.SuspendLayout();
            this.grpStudents.SuspendLayout();
            this.SuspendLayout();
            this.tabControl.Controls.Add(this.tabImport);
            this.tabControl.Controls.Add(this.tabPlans);
            this.tabControl.Controls.Add(this.tabWorkload);
            this.tabControl.Controls.Add(this.tabSettings);
            this.tabControl.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tabControl.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.tabControl.Location = new System.Drawing.Point(0, 0);
            this.tabControl.Name = "tabControl";
            this.tabControl.Size = new System.Drawing.Size(1000, 680);
            this.tabControl.TabIndex = 0;
            this.tabImport.Controls.Add(this.lblFilePath);
            this.tabImport.Controls.Add(this.txtFilePath);
            this.tabImport.Controls.Add(this.btnSelectFile);
            this.tabImport.Controls.Add(this.btnImport);
            this.tabImport.Controls.Add(this.lblDescription);
            this.tabImport.Controls.Add(this.txtDescription);
            this.tabImport.Controls.Add(this.txtLog);
            this.tabImport.Location = new System.Drawing.Point(4, 26);
            this.tabImport.Name = "tabImport";
            this.tabImport.Padding = new System.Windows.Forms.Padding(10);
            this.tabImport.Size = new System.Drawing.Size(992, 650);
            this.tabImport.TabIndex = 0;
            this.tabImport.Text = "Импорт";
            this.lblFilePath.AutoSize = true;
            this.lblFilePath.Location = new System.Drawing.Point(13, 20);
            this.lblFilePath.Text = "Файл PLX:";
            this.txtFilePath.Location = new System.Drawing.Point(13, 40);
            this.txtFilePath.Size = new System.Drawing.Size(750, 26);
            this.txtFilePath.ReadOnly = true;
            this.txtFilePath.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.btnSelectFile.Location = new System.Drawing.Point(773, 38);
            this.btnSelectFile.Size = new System.Drawing.Size(100, 30);
            this.btnSelectFile.Text = "Обзор...";
            this.btnSelectFile.Click += new System.EventHandler(this.btnSelectFile_Click);
            this.btnImport.Location = new System.Drawing.Point(13, 80);
            this.btnImport.Size = new System.Drawing.Size(200, 34);
            this.btnImport.Text = "Загрузить в базу данных";
            this.btnImport.BackColor = System.Drawing.Color.FromArgb(0, 120, 215);
            this.btnImport.ForeColor = System.Drawing.Color.White;
            this.btnImport.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnImport.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.btnImport.Click += new System.EventHandler(this.btnImport_Click);
            this.lblDescription.AutoSize = true;
            this.lblDescription.Location = new System.Drawing.Point(230, 88);
            this.lblDescription.Text = "Описание плана:";
            this.txtDescription.Location = new System.Drawing.Point(230, 108);
            this.txtDescription.Size = new System.Drawing.Size(400, 26);
            this.txtDescription.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.txtDescription.Text = "Основной вариант";
            this.txtLog.Location = new System.Drawing.Point(13, 145);
            this.txtLog.Size = new System.Drawing.Size(960, 480);
            this.txtLog.ReadOnly = true;
            this.txtLog.BackColor = System.Drawing.Color.FromArgb(30, 30, 30);
            this.txtLog.ForeColor = System.Drawing.Color.FromArgb(200, 255, 200);
            this.txtLog.Font = new System.Drawing.Font("Consolas", 10F);
            this.txtLog.ScrollBars = System.Windows.Forms.RichTextBoxScrollBars.Vertical;
            this.tabPlans.Controls.Add(this.btnDeletePlan);
            this.tabPlans.Controls.Add(this.btnRefreshPlans);
            this.tabPlans.Controls.Add(this.dgvPlans);
            this.tabPlans.Location = new System.Drawing.Point(4, 26);
            this.tabPlans.Name = "tabPlans";
            this.tabPlans.Padding = new System.Windows.Forms.Padding(10);
            this.tabPlans.Size = new System.Drawing.Size(992, 650);
            this.tabPlans.TabIndex = 3;
            this.tabPlans.Text = "Планы";
            this.btnRefreshPlans.Location = new System.Drawing.Point(13, 13);
            this.btnRefreshPlans.Size = new System.Drawing.Size(150, 30);
            this.btnRefreshPlans.Text = "Обновить список";
            this.btnRefreshPlans.BackColor = System.Drawing.Color.FromArgb(0, 120, 215);
            this.btnRefreshPlans.ForeColor = System.Drawing.Color.White;
            this.btnRefreshPlans.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnRefreshPlans.Font = new System.Drawing.Font("Segoe UI", 9.5F, System.Drawing.FontStyle.Bold);
            this.btnRefreshPlans.Click += new System.EventHandler(this.btnRefreshPlans_Click);
            this.btnDeletePlan.Location = new System.Drawing.Point(173, 13);
            this.btnDeletePlan.Size = new System.Drawing.Size(150, 30);
            this.btnDeletePlan.Text = "Удалить план";
            this.btnDeletePlan.BackColor = System.Drawing.Color.FromArgb(0, 120, 215);
            this.btnDeletePlan.ForeColor = System.Drawing.Color.White;
            this.btnDeletePlan.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnDeletePlan.Font = new System.Drawing.Font("Segoe UI", 9.5F, System.Drawing.FontStyle.Bold);
            this.btnDeletePlan.Name = "btnDeletePlan";
            this.btnDeletePlan.Click += new System.EventHandler(this.btnDeletePlan_Click);
            this.dgvPlans.Location = new System.Drawing.Point(13, 55);
            this.dgvPlans.Size = new System.Drawing.Size(960, 570);
            this.dgvPlans.ReadOnly = true;
            this.dgvPlans.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvPlans.AllowUserToAddRows = false;
            this.dgvPlans.RowHeadersVisible = false;
            this.dgvPlans.BackgroundColor = System.Drawing.Color.White;
            this.dgvPlans.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this.dgvPlans.ColumnHeadersDefaultCellStyle.Font = new System.Drawing.Font("Segoe UI", 9.5F, System.Drawing.FontStyle.Bold);
            this.dgvPlans.AlternatingRowsDefaultCellStyle.BackColor = System.Drawing.Color.FromArgb(245, 245, 250);
            this.dgvPlans.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvPlans.MultiSelect = false;
            this.tabWorkload.Controls.Add(this.clbSpecialities);
            this.tabWorkload.Controls.Add(this.lblSelectPlans);
            this.tabWorkload.Controls.Add(this.lblSpeciality);
            this.tabWorkload.Controls.Add(this.cmbSpeciality);
            this.tabWorkload.Controls.Add(this.lblGroup);
            this.tabWorkload.Controls.Add(this.cmbGroup);
            this.tabWorkload.Controls.Add(this.lblYear);
            this.tabWorkload.Controls.Add(this.numYear);
            this.tabWorkload.Controls.Add(this.lblMode);
            this.tabWorkload.Controls.Add(this.cmbMode);
            this.tabWorkload.Controls.Add(this.lblCourse);
            this.tabWorkload.Controls.Add(this.cmbCourse);
            this.tabWorkload.Controls.Add(this.btnCalculate);
            this.tabWorkload.Controls.Add(this.tabResults);
            this.tabWorkload.Controls.Add(this.lblSp);
            this.tabWorkload.Controls.Add(this.lblSpValue);
            this.tabWorkload.Location = new System.Drawing.Point(4, 26);
            this.tabWorkload.Name = "tabWorkload";
            this.tabWorkload.Padding = new System.Windows.Forms.Padding(10);
            this.tabWorkload.Size = new System.Drawing.Size(992, 650);
            this.tabWorkload.TabIndex = 1;
            this.tabWorkload.Text = "Нагрузка";
            this.lblSpeciality.AutoSize = true;
            this.lblSpeciality.Location = new System.Drawing.Point(13, 15);
            this.lblSpeciality.Text = "Направление:";
            this.cmbSpeciality.Location = new System.Drawing.Point(13, 33);
            this.cmbSpeciality.Size = new System.Drawing.Size(460, 26);
            this.cmbSpeciality.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbSpeciality.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.cmbSpeciality.SelectedIndexChanged += new System.EventHandler(this.cmbSpeciality_SelectedIndexChanged);
            this.lblGroup.AutoSize = true;
            this.lblGroup.Location = new System.Drawing.Point(477, 15);
            this.lblGroup.Text = "Группа:";
            this.cmbGroup.Location = new System.Drawing.Point(477, 33);
            this.cmbGroup.Size = new System.Drawing.Size(120, 26);
            this.cmbGroup.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbGroup.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.lblYear.AutoSize = true;
            this.lblYear.Location = new System.Drawing.Point(498, 15);
            this.lblYear.Text = "Учебный год:";
            this.lblYear.Visible = false;
            this.numYear.Location = new System.Drawing.Point(498, 33);
            this.numYear.Size = new System.Drawing.Size(90, 26);
            this.numYear.Minimum = 2000;
            this.numYear.Maximum = 2100;
            this.numYear.Value = DateTime.Now.Year;
            this.numYear.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.numYear.Visible = false;
            this.lblMode.AutoSize = true;
            this.lblMode.Location = new System.Drawing.Point(602, 15);
            this.lblMode.Text = "Режим расчёта:";
            this.cmbMode.Location = new System.Drawing.Point(602, 33);
            this.cmbMode.Size = new System.Drawing.Size(220, 26);
            this.cmbMode.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbMode.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.cmbMode.Items.Add("3.1 — Весь план по кафедрам");
            this.cmbMode.Items.Add("3.2 — Курс одного плана");
            this.cmbMode.Items.Add("3.3 — Курс нескольких планов");
            this.cmbMode.SelectedIndex = 0;
            this.cmbMode.SelectedIndexChanged += new System.EventHandler(this.cmbMode_SelectedIndexChanged);
            this.lblCourse.AutoSize = true;
            this.lblCourse.Location = new System.Drawing.Point(825, 15);
            this.lblCourse.Text = "Курс:";
            this.cmbCourse.Location = new System.Drawing.Point(825, 33);
            this.cmbCourse.Size = new System.Drawing.Size(100, 26);
            this.cmbCourse.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbCourse.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.cmbCourse.Items.Add("1 курс");
            this.cmbCourse.Items.Add("2 курс");
            this.cmbCourse.Items.Add("3 курс");
            this.cmbCourse.Items.Add("4 курс");
            this.cmbCourse.SelectedIndex = 0;
            this.cmbCourse.Enabled = false;
            this.clbSpecialities.Location = new System.Drawing.Point(13, 33);
            this.clbSpecialities.Size = new System.Drawing.Size(580, 72);
            this.clbSpecialities.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.clbSpecialities.CheckOnClick = true;
            this.clbSpecialities.Visible = false;
            this.clbSpecialities.Name = "clbSpecialities";
            this.clbSpecialities.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblSelectPlans.Location = new System.Drawing.Point(13, 15);
            this.lblSelectPlans.Size = new System.Drawing.Size(485, 18);
            this.lblSelectPlans.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.lblSelectPlans.ForeColor = System.Drawing.Color.Black;
            this.lblSelectPlans.Text = "Выберите планы для сравнения:";
            this.lblSelectPlans.Visible = false;
            this.lblSelectPlans.Name = "lblSelectPlans";
            this.btnCalculate.Location = new System.Drawing.Point(930, 29);
            this.btnCalculate.Size = new System.Drawing.Size(50, 34);
            this.btnCalculate.Text = "▶";
            this.btnCalculate.BackColor = System.Drawing.Color.FromArgb(0, 150, 80);
            this.btnCalculate.ForeColor = System.Drawing.Color.White;
            this.btnCalculate.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnCalculate.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold);
            this.btnCalculate.Click += new System.EventHandler(this.btnCalculate_Click);
            this.tabResults.Controls.Add(this.tabDisciplines);
            this.tabResults.Controls.Add(this.tabDepartments);
            this.tabResults.Location = new System.Drawing.Point(13, 72);
            this.tabResults.Size = new System.Drawing.Size(967, 545);
            this.tabResults.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this.tabDisciplines.Controls.Add(this.dgvResults);
            this.tabDisciplines.Location = new System.Drawing.Point(4, 26);
            this.tabDisciplines.Size = new System.Drawing.Size(959, 515);
            this.tabDisciplines.Text = "По дисциплинам";
            this.tabDepartments.Controls.Add(this.dgvDepartments);
            this.tabDepartments.Location = new System.Drawing.Point(4, 26);
            this.tabDepartments.Size = new System.Drawing.Size(959, 515);
            this.tabDepartments.Text = "По кафедрам";
            this.dgvResults.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dgvResults.ReadOnly = true;
            this.dgvResults.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvResults.AllowUserToAddRows = false;
            this.dgvResults.RowHeadersVisible = false;
            this.dgvResults.BackgroundColor = System.Drawing.Color.White;
            this.dgvResults.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this.dgvResults.ColumnHeadersDefaultCellStyle.Font = new System.Drawing.Font("Segoe UI", 9.5F, System.Drawing.FontStyle.Bold);
            this.dgvResults.AlternatingRowsDefaultCellStyle.BackColor = System.Drawing.Color.FromArgb(245, 245, 250);
            this.dgvDepartments.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dgvDepartments.ReadOnly = true;
            this.dgvDepartments.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvDepartments.AllowUserToAddRows = false;
            this.dgvDepartments.RowHeadersVisible = false;
            this.dgvDepartments.BackgroundColor = System.Drawing.Color.White;
            this.dgvDepartments.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this.dgvDepartments.ColumnHeadersDefaultCellStyle.Font = new System.Drawing.Font("Segoe UI", 9.5F, System.Drawing.FontStyle.Bold);
            this.dgvDepartments.AlternatingRowsDefaultCellStyle.BackColor = System.Drawing.Color.FromArgb(245, 245, 250);
            this.lblSp.AutoSize = true;
            this.lblSp.Location = new System.Drawing.Point(13, 627);
            this.lblSp.Font = new System.Drawing.Font("Segoe UI", 11F, System.Drawing.FontStyle.Bold);
            this.lblSp.Text = "Суммарное число ставок (Sп):";
            this.lblSpValue.AutoSize = true;
            this.lblSpValue.Location = new System.Drawing.Point(280, 627);
            this.lblSpValue.Font = new System.Drawing.Font("Segoe UI", 11F, System.Drawing.FontStyle.Bold);
            this.lblSpValue.ForeColor = System.Drawing.Color.FromArgb(0, 120, 215);
            this.lblSpValue.Text = "—";
            this.tabSettings.Controls.Add(this.grpFormula);
            this.tabSettings.Controls.Add(this.grpGroups);
            this.tabSettings.Controls.Add(this.grpStudents);
            this.tabSettings.Location = new System.Drawing.Point(4, 26);
            this.tabSettings.Name = "tabSettings";
            this.tabSettings.Padding = new System.Windows.Forms.Padding(10);
            this.tabSettings.Size = new System.Drawing.Size(992, 650);
            this.tabSettings.TabIndex = 2;
            this.tabSettings.Text = "Настройки";
            this.grpFormula.Controls.Add(this.lblSpecSettings);
            this.grpFormula.Controls.Add(this.cmbSpecSettings);
            this.grpFormula.Controls.Add(this.lblYearSettings);
            this.grpFormula.Controls.Add(this.numYearSettings);
            this.grpFormula.Controls.Add(this.lblStudentsPerRate);
            this.grpFormula.Controls.Add(this.numStudentsPerRate);
            this.grpFormula.Controls.Add(this.lblHoursCW);
            this.grpFormula.Controls.Add(this.numHoursCW);
            this.grpFormula.Controls.Add(this.lblHoursCP);
            this.grpFormula.Controls.Add(this.numHoursCP);
            this.grpFormula.Controls.Add(this.lblHoursGW);
            this.grpFormula.Controls.Add(this.numHoursGW);
            this.grpFormula.Controls.Add(this.btnSaveFormula);
            this.grpFormula.Location = new System.Drawing.Point(13, 13);
            this.grpFormula.Size = new System.Drawing.Size(460, 320);
            this.grpFormula.Text = "Параметры формулы";
            this.grpFormula.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            int fy = 30;
            this.lblSpecSettings.AutoSize = true;
            this.lblSpecSettings.Location = new System.Drawing.Point(10, fy);
            this.lblSpecSettings.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this.lblSpecSettings.Text = "Направление:";
            this.cmbSpecSettings.Location = new System.Drawing.Point(10, fy + 20);
            this.cmbSpecSettings.Size = new System.Drawing.Size(430, 26);
            this.cmbSpecSettings.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbSpecSettings.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this.cmbSpecSettings.SelectedIndexChanged += new System.EventHandler(this.cmbSpecSettings_SelectedIndexChanged);
            this.lblYearSettings.AutoSize = true;
            this.lblYearSettings.Location = new System.Drawing.Point(300, fy);
            this.lblYearSettings.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this.lblYearSettings.Text = "Год:";
            this.lblYearSettings.Visible = false;
            this.numYearSettings.Location = new System.Drawing.Point(300, fy + 20);
            this.numYearSettings.Visible = false;
            this.numYearSettings.Size = new System.Drawing.Size(90, 26);
            this.numYearSettings.Minimum = 2000;
            this.numYearSettings.Maximum = 2100;
            this.numYearSettings.Value = DateTime.Now.Year;
            this.numYearSettings.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this.numYearSettings.ValueChanged += new System.EventHandler(this.numYearSettings_ValueChanged);
            fy += 65;
            AddLabelAndNumeric(this.lblStudentsPerRate, this.numStudentsPerRate, "Студентов на ставку (Xст):", 14, 10, fy);
            fy += 50;
            AddLabelAndNumeric(this.lblHoursCW, this.numHoursCW, "Часов на КР (hКР):", 2, 10, fy);
            fy += 50;
            AddLabelAndNumeric(this.lblHoursCP, this.numHoursCP, "Часов на КП (hКП):", 4, 10, fy);
            fy += 50;
            AddLabelAndNumeric(this.lblHoursGW, this.numHoursGW, "Часов на ВКР (hВКР):", 21, 10, fy);
            this.btnSaveFormula.Location = new System.Drawing.Point(10, 290);
            this.btnSaveFormula.Size = new System.Drawing.Size(180, 30);
            this.btnSaveFormula.Text = "Сохранить";
            this.btnSaveFormula.BackColor = System.Drawing.Color.FromArgb(0, 120, 215);
            this.btnSaveFormula.ForeColor = System.Drawing.Color.White;
            this.btnSaveFormula.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnSaveFormula.Font = new System.Drawing.Font("Segoe UI", 9.5F, System.Drawing.FontStyle.Bold);
            this.btnSaveFormula.Click += new System.EventHandler(this.btnSaveFormula_Click);
            this.grpGroups.Controls.Add(this.lblGroupName);
            this.grpGroups.Controls.Add(this.txtGroupName);
            this.grpGroups.Controls.Add(this.lblGroupProfile);
            this.grpGroups.Controls.Add(this.cmbGroupProfile);
            this.grpGroups.Controls.Add(this.btnAddGroup);
            this.grpGroups.Controls.Add(this.btnDeleteGroup);
            this.grpGroups.Location = new System.Drawing.Point(490, 13);
            this.grpGroups.Size = new System.Drawing.Size(460, 150);
            this.grpGroups.Text = "Добавить группу";
            this.grpGroups.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.lblGroupProfile.AutoSize = true;
            this.lblGroupProfile.Location = new System.Drawing.Point(10, 30);
            this.lblGroupProfile.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this.lblGroupProfile.Text = "Направление:";
            this.cmbGroupProfile.Location = new System.Drawing.Point(10, 50);
            this.cmbGroupProfile.Size = new System.Drawing.Size(430, 26);
            this.cmbGroupProfile.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbGroupProfile.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this.lblGroupName.AutoSize = true;
            this.lblGroupName.Location = new System.Drawing.Point(10, 85);
            this.lblGroupName.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this.lblGroupName.Text = "Название группы:";
            this.txtGroupName.Location = new System.Drawing.Point(10, 105);
            this.txtGroupName.Size = new System.Drawing.Size(200, 26);
            this.txtGroupName.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this.btnAddGroup.Location = new System.Drawing.Point(220, 103);
            this.btnAddGroup.Size = new System.Drawing.Size(120, 30);
            this.btnAddGroup.Text = "Добавить";
            this.btnAddGroup.BackColor = System.Drawing.Color.FromArgb(0, 150, 80);
            this.btnAddGroup.ForeColor = System.Drawing.Color.White;
            this.btnAddGroup.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnAddGroup.Font = new System.Drawing.Font("Segoe UI", 9.5F, System.Drawing.FontStyle.Bold);
            this.btnAddGroup.Click += new System.EventHandler(this.btnAddGroup_Click);
            this.btnDeleteGroup.Location = new System.Drawing.Point(350, 103);
            this.btnDeleteGroup.Size = new System.Drawing.Size(100, 30);
            this.btnDeleteGroup.Text = "Удалить";
            this.btnDeleteGroup.BackColor = System.Drawing.Color.FromArgb(0, 120, 215);
            this.btnDeleteGroup.ForeColor = System.Drawing.Color.White;
            this.btnDeleteGroup.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnDeleteGroup.Font = new System.Drawing.Font("Segoe UI", 9.5F, System.Drawing.FontStyle.Bold);
            this.btnDeleteGroup.Name = "btnDeleteGroup";
            this.btnDeleteGroup.Click += new System.EventHandler(this.btnDeleteGroup_Click);
            this.grpStudents.Controls.Add(this.lblStudentGroup);
            this.grpStudents.Controls.Add(this.cmbStudentGroup);
            this.grpStudents.Controls.Add(this.lblStudentYear);
            this.grpStudents.Controls.Add(this.numStudentYear);
            this.grpStudents.Controls.Add(this.lblStudentCount);
            this.grpStudents.Controls.Add(this.numStudentCount);
            this.grpStudents.Controls.Add(this.btnSaveStudents);
            this.grpStudents.Location = new System.Drawing.Point(490, 175);
            this.grpStudents.Size = new System.Drawing.Size(460, 180);
            this.grpStudents.Text = "Количество студентов";
            this.grpStudents.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.lblStudentGroup.AutoSize = true;
            this.lblStudentGroup.Location = new System.Drawing.Point(10, 30);
            this.lblStudentGroup.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this.lblStudentGroup.Text = "Группа:";
            this.cmbStudentGroup.Location = new System.Drawing.Point(10, 50);
            this.cmbStudentGroup.Size = new System.Drawing.Size(200, 26);
            this.cmbStudentGroup.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbStudentGroup.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this.lblStudentYear.AutoSize = true;
            this.lblStudentYear.Location = new System.Drawing.Point(220, 30);
            this.lblStudentYear.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this.lblStudentYear.Text = "Учебный год:";
            this.lblStudentYear.Visible = true;
            this.numStudentYear.Location = new System.Drawing.Point(220, 50);
            this.numStudentYear.Size = new System.Drawing.Size(90, 26);
            this.numStudentYear.Minimum = 2000;
            this.numStudentYear.Maximum = 2100;
            this.numStudentYear.Value = DateTime.Now.Year;
            this.numStudentYear.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this.numStudentYear.Visible = true;
            this.lblStudentCount.AutoSize = true;
            this.lblStudentCount.Location = new System.Drawing.Point(10, 90);
            this.lblStudentCount.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this.lblStudentCount.Text = "Количество студентов:";
            this.numStudentCount.Location = new System.Drawing.Point(10, 110);
            this.numStudentCount.Size = new System.Drawing.Size(100, 26);
            this.numStudentCount.Minimum = 0;
            this.numStudentCount.Maximum = 500;
            this.numStudentCount.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this.btnSaveStudents.Location = new System.Drawing.Point(120, 108);
            this.btnSaveStudents.Size = new System.Drawing.Size(120, 30);
            this.btnSaveStudents.Text = "Сохранить";
            this.btnSaveStudents.BackColor = System.Drawing.Color.FromArgb(0, 120, 215);
            this.btnSaveStudents.ForeColor = System.Drawing.Color.White;
            this.btnSaveStudents.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnSaveStudents.Font = new System.Drawing.Font("Segoe UI", 9.5F, System.Drawing.FontStyle.Bold);
            this.btnSaveStudents.Click += new System.EventHandler(this.btnSaveStudents_Click);
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1000, 680);
            this.Controls.Add(this.tabControl);
            this.MinimumSize = new System.Drawing.Size(1016, 718);
            this.Name = "MainForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Анализ учебной нагрузки кафедры ФиПМ ВлГУ";
            this.tabControl.ResumeLayout(false);
            this.tabImport.ResumeLayout(false);
            this.tabImport.PerformLayout();
            this.tabPlans.ResumeLayout(false);
            this.tabWorkload.ResumeLayout(false);
            this.tabWorkload.PerformLayout();
            this.tabResults.ResumeLayout(false);
            this.tabDisciplines.ResumeLayout(false);
            this.tabDepartments.ResumeLayout(false);
            this.tabSettings.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)this.numYear).EndInit();
            ((System.ComponentModel.ISupportInitialize)this.dgvResults).EndInit();
            ((System.ComponentModel.ISupportInitialize)this.dgvDepartments).EndInit();
            ((System.ComponentModel.ISupportInitialize)this.dgvPlans).EndInit();
            ((System.ComponentModel.ISupportInitialize)this.numYearSettings).EndInit();
            ((System.ComponentModel.ISupportInitialize)this.numStudentsPerRate).EndInit();
            ((System.ComponentModel.ISupportInitialize)this.numHoursCW).EndInit();
            ((System.ComponentModel.ISupportInitialize)this.numHoursCP).EndInit();
            ((System.ComponentModel.ISupportInitialize)this.numHoursGW).EndInit();
            ((System.ComponentModel.ISupportInitialize)this.numStudentYear).EndInit();
            ((System.ComponentModel.ISupportInitialize)this.numStudentCount).EndInit();
            this.grpFormula.ResumeLayout(false);
            this.grpFormula.PerformLayout();
            this.grpGroups.ResumeLayout(false);
            this.grpGroups.PerformLayout();
            this.grpStudents.ResumeLayout(false);
            this.grpStudents.PerformLayout();
            this.ResumeLayout(false);
        }
        private void AddLabelAndNumeric(System.Windows.Forms.Label lbl, System.Windows.Forms.NumericUpDown num,
            string text, int defaultVal, int x, int y)
        {
            lbl.AutoSize = true;
            lbl.Location = new System.Drawing.Point(x, y);
            lbl.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            lbl.Text = text;
            this.grpFormula.Controls.Add(lbl);
            num.Location = new System.Drawing.Point(x, y + 20);
            num.Size = new System.Drawing.Size(100, 26);
            num.Minimum = 0;
            num.Maximum = 9999;
            num.Value = defaultVal;
            num.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this.grpFormula.Controls.Add(num);
        }
        private System.Windows.Forms.TabControl tabControl;
        private System.Windows.Forms.TabPage tabImport;
        private System.Windows.Forms.TabPage tabPlans;
        private System.Windows.Forms.TabPage tabWorkload;
        private System.Windows.Forms.TabPage tabSettings;
        private System.Windows.Forms.Button btnSelectFile;
        private System.Windows.Forms.TextBox txtFilePath;
        private System.Windows.Forms.Button btnImport;
        private System.Windows.Forms.RichTextBox txtLog;
        private System.Windows.Forms.Label lblFilePath;
        private System.Windows.Forms.Label lblDescription;
        private System.Windows.Forms.TextBox txtDescription;
        private System.Windows.Forms.DataGridView dgvPlans;
        private System.Windows.Forms.Button btnDeletePlan;
        private System.Windows.Forms.Button btnRefreshPlans;
        private System.Windows.Forms.Label lblSpeciality;
        private System.Windows.Forms.ComboBox cmbSpeciality;
        private System.Windows.Forms.CheckedListBox clbSpecialities;
        private System.Windows.Forms.Label lblSelectPlans;
        private System.Windows.Forms.Label lblGroup;
        private System.Windows.Forms.ComboBox cmbGroup;
        private System.Windows.Forms.Label lblYear;
        private System.Windows.Forms.NumericUpDown numYear;
        private System.Windows.Forms.Label lblMode;
        private System.Windows.Forms.ComboBox cmbMode;
        private System.Windows.Forms.Label lblCourse;
        private System.Windows.Forms.ComboBox cmbCourse;
        private System.Windows.Forms.Button btnCalculate;
        private System.Windows.Forms.TabControl tabResults;
        private System.Windows.Forms.TabPage tabDisciplines;
        private System.Windows.Forms.TabPage tabDepartments;
        private System.Windows.Forms.DataGridView dgvResults;
        private System.Windows.Forms.DataGridView dgvDepartments;
        private System.Windows.Forms.Label lblSp;
        private System.Windows.Forms.Label lblSpValue;
        private System.Windows.Forms.GroupBox grpFormula;
        private System.Windows.Forms.Label lblSpecSettings;
        private System.Windows.Forms.ComboBox cmbSpecSettings;
        private System.Windows.Forms.Label lblYearSettings;
        private System.Windows.Forms.NumericUpDown numYearSettings;
        private System.Windows.Forms.Label lblStudentsPerRate;
        private System.Windows.Forms.NumericUpDown numStudentsPerRate;
        private System.Windows.Forms.Label lblHoursCW;
        private System.Windows.Forms.NumericUpDown numHoursCW;
        private System.Windows.Forms.Label lblHoursCP;
        private System.Windows.Forms.NumericUpDown numHoursCP;
        private System.Windows.Forms.Label lblHoursGW;
        private System.Windows.Forms.NumericUpDown numHoursGW;
        private System.Windows.Forms.Button btnSaveFormula;
        private System.Windows.Forms.GroupBox grpGroups;
        private System.Windows.Forms.Label lblGroupName;
        private System.Windows.Forms.TextBox txtGroupName;
        private System.Windows.Forms.Label lblGroupProfile;
        private System.Windows.Forms.ComboBox cmbGroupProfile;
        private System.Windows.Forms.Button btnAddGroup;
        private System.Windows.Forms.Button btnDeleteGroup;
        private System.Windows.Forms.GroupBox grpStudents;
        private System.Windows.Forms.Label lblStudentGroup;
        private System.Windows.Forms.ComboBox cmbStudentGroup;
        private System.Windows.Forms.Label lblStudentYear;
        private System.Windows.Forms.NumericUpDown numStudentYear;
        private System.Windows.Forms.Label lblStudentCount;
        private System.Windows.Forms.NumericUpDown numStudentCount;
        private System.Windows.Forms.Button btnSaveStudents;
    }
}